### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by pgporada** [hashivim/vim-nomadproject#1]
I'm working on the [syntax for the Nomad Project](https://github.com/pgporada/vim-hashicorp-tools). I saw http://hashivim.github.io/ and would like to join this organization if, big assumption, I can get this syntax completed. This is ultimately up to you.

Here is my experience with the Hashicorp tools to date. I've been a vim guy for many years and am a systems administrator at heart.

- Terraform: 1 year 2 months
- Consul: 11 months
- Nomad: 3 months

I use your test-kitchen vim syntax and it helps keep me sane.

Here is the WIP version of the nomad syntax.
https://imgur.com/a/V2mv9

**Comment by mcornick** [comment]
Thanks, I've sent you an invitation. I don't have time to work on these much any more, and Nomad is one of the tools I don't use, so I really appreciate the help!
